use LoLDb;

select * from Equipment;
--select * from Equipped;
select * from EquipType;
--select * from EquipTypeOf;

insert into EquipTypeOf values
('Health Potion',0),
('Hunters Machete',0),
('Skirmishers Sabre',0),
('Poachers Knife',0),
('Rangers Trailblazer',0),
('Stalkers Blade',0),
('Health Potion',1),
('Mana Potion',1),
('Stealth Ward',1),
('Vision Ward',1),
('Crystalline Flask',1),
('Long Sword',1),
('Ancient Coin',1),
('Spellthiefs Edge',1),
('Relic Shield',1),
('Dorans Ring',1),
('Dorans Shield',1),
('Dorans blade',1),
('Health Potion',2),
('Mana Potion',2),
('Stealth Ward',2),
('Vision Ward',2),
('Oracles Extract',2),
('Crystalline Flask',2),
('Elixir of Iron',2),
('Elixir of Ruin',2),
('Elixir of Sorcery',2),
('Elixir of Wrath',2),
('Ancient Coin',3),
('Spellthiefs Edge',3),
('Relic Shield',3),
('Avarice Blade',3),
('Targons Brace',3),
('Frostfang',3),
('Nomads Medallion',3),
('Grezs Spectral Lantern',3),
('Talisman of Ascension',3),
('Frost Queens Claim',3),
('Face of the Mountain',3),
('Stealth Ward',4),
('Vision Ward',4),
('Oracles Extract',4),
('Sightstone',4),
('Ruby Sightstone',4),
('Grezs Spectral Lantern',4),
('Hextech Sweeper',4),
('The Lightbringer',4),
('Twin Shadows',4),
('Cloth Armor',5),
('Chain Vest',5),
('Glacial Shroud',5),
('Raptor Cloak',5),
('Ninja Tabi',5),
('Guardians Horn',5),
('Wardens Mail',5),
('Seekers Armguard',5),
('Thornmail',5),
('Hextech Sweeper',5),
('Frozen Heart',5),
('Ohmwrecker',5),
('Sunfire Cape',5),
('Guardian Angel',5),
('ZzRot Portal',5),
('Randuins Omen',5),
('Iceborn Gauntlet',5),
('Zhonyas Hourglass',5),
('Wooglets Witchcap',5),
('Relic Shield',6),
('Elixir of Ruin',6),
('Ruby Crystal',6),
('Dorans Ring',6),
('Dorans Shield',6),
('Dorans Blade',6),
('Crystalline Bracer',6),
('Sightstone',6),
('kindlegem',6),
('Targons Brace',6),
('Prospectors Ring',6),
('Prospectors Blade',6),
('Giants Belt',6),
('Guardians Horn',6),
('Spectres Cowl',6),
('Catalyst the Protector',6),
('Phage',6),
('Haunting Guise',6),
('Ruby Sightstone',6),
('Aegis of the Legion',6),
('Hextech Sweeper',6),
('Face of the Mountain',6),
('Stalkers Blade',6),
('Skirmishers Sabre',6),
('Rangers Trailblazer',6),
('Zekes Herald',6),
('Overlords Bloodmail',6),
('Righteous Glory',6),
('Odyns Veil',6),
('Warmog''s Armor',6),
('Ohmwrecker',6),
('Sunfire Cape',6),
('Entropy',6),
('Spirit Visage',6),
('Banshees Veil',6),
('Locket of the Iron Solari',6),
('Rod of Ages',6),
('Randuins Omen',6),
('Rylais Crystal Scepter',6),
('Liandrys Torment',6),
('Banner of Command',6),
('The Black Cleaver',6),
('Frozen Mallet',6),
('Trinity Force',6),
('Aegis of the Legion',7),
('Ancient Coin',7),
('Crystalline Bracer',7),
('Crystalline Flask',7),
('Face of the Mountain',7),
('Guardians Horn',7),
('Locket of the Iron Solari',7),
('Nomads Medallion',7),
('Orb of Winter',7),
('Raptor Cloak',7),
('Ravenous Hydra',7),
('Rejuvenation Bead',7),
('Righteous Glory',7),
('Spectres Cowl',7),
('Talisman of Ascension',7),
('Targons Brace',7),
('Tiamat',7),
('Warmog''s Armor',7),
('ZzRot Portal',7),
('Abyssal Scepter',8),
('Aegis of the Legion',8),
('Athenes Unholy Grail',8),
('Banner of Command',8),
('Guardian Angel',8),
('Guardians Horn',8),
('Locket of the Iron Solari',8),
('Maw of Malmortius',8),
('Mercurial Scimitar',8),
('Mercurys Treads',8),
('Mikaels Crucible',8),
('Negatron Cloak',8),
('Null-Magic Mantle',8),
('Odyns Veil',8),
('Orb of Winter',8),
('Quicksilver Sash',8),
('Spirit Visage',8),
('ZzRot Portal',8),
('Berserkers Greaves',9),
('Blade of the Ruined King',9),
('Dagger',9),
('Grezs Spectral Lantern',9),
('Guinsoos Rageblade',9),
('Madrayylmaos Razors',9),
('Nashors Tooth',9),
('Phantom Dancer',9),
('Recurve Bow',9),
('Runaans Hurricane',9),
('Statikk Shiv',9),
('Stinger',9),
('Wits End',9),
('Youmuus Ghostblade',9),
('Zeal',9),
('Zephyr',9),
('Avarice Blade',10),
('Brawlers Gloves',10),
('Cloak of Agility',10),
('Infinity Edge',10),
('Lord Van Damms Pillager',10),
('Phantom Dancer',10),
('Zeal',10),
('Youmuus Ghostblade',10),
('Wicked Hatchet',10),
('Trinity Force',10),
('The Lightbringer',10),
('B.F. Sword',11),
('Bilgewater Cutlass',11),
('Blade of the Ruined King',11),
('Dorans Blade',11),
('Entropy',11),
('Essence Reaver',11),
('Frozen Mallet',11),
('Grezs Spectral Lantern',11),
('Hexdrinker',11),
('Hunters Machete',11),
('Infinity Edge',11),
('Last Whisper',11),
('Long Sword',11),
('Lord Van Damms Pillager',11),
('Maw of Malmortius',11),
('Mercurial Scimitar',11),
('Muramana',11),
('Phage',11),
('Pickaxe',11),
('Poachers Knife',11),
('Prospectors Blade',11),
('Ravenous Hydra',11),
('Sanguine Blade',11),
('Skirmishers Sabre',11),
('Stalkers Blade',11),
('Sword of the Occult',11),
('The Black Cleaver',11),
('The Bloodthirster',11),
('The Brutalizer',11),
('The Lightbringer',11),
('Tiamat',11),
('Trinity Force',11),
('Wicked Hatchet',11),
('Youmuus Ghostblade',11),
('Zephyr',11),
('Bilgewater Cutlass',12),
('Blade of the Ruined King',12),
('Essence Reaver',12),
('Dorans Blade',12),
('Guinsoos Rageblade',12),
('Hextech Gunblade',12),
('Prospectors Blade',12),
('Zekes Herald',12),
('Vampiric Scepter',12),
('The Bloodthirster',12),
('Sanguine Blade',12),
('Ravenous Hydra',12),
('Ardent Censer',13),
('Athenes Unholy Grail',13),
('Banner of Command',13),
('Essence Reaver',13),
('Face of the Mountain',13),
('Fiendish Codex',13),
('Forbidden Idol',13),
('Frost Queens Claim',13),
('Frozen Heart',13),
('Glacial Shroud',13),
('Hextech Sweeper',13),
('Iceborn Gauntlet',13),
('Ionian Boots of Lucidity',13),
('Kindlegem',13),
('Locket of the Iron Solari',13),
('Mikaels Crucible',13),
('Morellonomicon',13),
('Nashors Tooth',13),
('Spirit Visage',13),
('Stinger',13),
('Talisman of Ascension',13),
('The Black Cleaver',13),
('The Brutalizer',13),
('Twin Shadows',13),
('Will of the Ancients',13),
('Youmuus Ghostblade',13),
('Zekes Herald',13),
('Zephyr',13),
('Archangels Staff',14),
('Catalyst the Protector',14),
('Frozen Heart',14),
('Glacial Shroud',14),
('Iceborn Gauntlet',14),
('Lich Bane',14),
('Sapphire Crystal',14),
('Rod of Ages',14),
('Righteous Glory',14),
('Perfect Hex Core',14),
('Odyns Veil',14),
('Muramana',14),
('Seraphs Embrace',14),
('Sheen',14),
('Tear of the Goddess',14),
('The Hex Core MK-1',14),
('The Hex Core MK-2',14),
('Trinity Force',14),
('Ancient Coin',15),
('Faerie Charm',15),
('Muramana',15),
('Archangels Staff',15),
('Forbidden Idol',15),
('Nomads Medallion',15),
('Prospectors Ring',15),
('Ardent Censer',15),
('Athenes Unholy Grail',15),
('Frostfang',15),
('Seraphs Embrace',15),
('Spellthiefs Edge',15),
('Crystalline Flask',15),
('Mikaels Crucible',15),
('Talisman of Ascension',15),
('Tear of the Goddess',15),
('Morellonomicon',15),
('Dorans Ring',15),
('Abyssal Scepter',16),
('Aether Wisp',16),
('Amplifying Tome',16),
('Archangels Staff',16),
('Ardent Censer',16),
('Athenes Unholy Grail',16),
('Banner of Command',16),
('Blasting Wand',16),
('Dorans Ring',16),
('Fiendish Codex',16),
('Frost Queens Claim',16),
('Frostfang',16),
('Guinsoos Rageblade',16),
('Haunting Guise',16),
('Hextech Gunblade',16),
('Hextech Revolver',16),
('Iceborn Gauntlet',16),
('Liandrys Torment',16),
('Lich Bane',16),
('Mejais Soulstealer',16),
('Moonflair Spellblade',16),
('Morellonomicon',16),
('Nashors Tooth',16),
('Needlessly Large Rod',16),
('Ohmwrecker',16),
('Perfect Hex Core',16),
('Prospectors Ring',16),
('Prototype Hex Core',16),
('Rabadons Deathcap',16),
('Rod of Ages',16),
('Rylais Crystal Scepter',16),
('Seekers Armguard',16),
('Seraphs Embrace',16),
('Sheen',16),
('Spellthiefs Edge',16),
('The Hex Core MK-1',16),
('The Hex Core MK-2',16),
('Trinity Force',16),
('Twin Shadows',16),
('Void Staff',16),
('Will of the Ancients',16),
('Wooglets Witchcap',16),
('Zhonyas Hourglass',16),
('Berserkers Greaves',17),
('Boots of Mobility',17),
('Boots of Speed',17),
('Boots of Swiftness',17),
('Ionian Boots of Lucidity',17),
('Mercurys Treads',17),
('Ninja Tabi',17),
('Sorcerers Shoes',17),
('Aether Wisp',18),
('Ardent Censer',18),
('Guardians Horn',18),
('Lich Bane',18),
('Mercurial Scimitar',18),
('Nomads Medallion',18),
('Phantom Dancer',18),
('Statikk Shiv',18),
('Talisman of Ascension',18),
('Trinity Force',18),
('Twin Shadows',18),
('Youmuus Ghostblade',18),
('Zeal',18),
('Zephyr',18);
