use LoLDb;

Insert into ChampionBasic Values
('Aatrox', 'The Darkin Blade', 'M'),
('Ahri', 'The Nine-Tailed Fox', 'F'),
('Akali', 'The Fist of Shadow', 'F'),
('Alistar', 'The Minotaur', 'M'),
('Amumu', 'The Sad Mummy', 'M'),
('Anivia', 'The Cryophoenix', 'F'),
('Annie', 'The Dark Child', 'F'),
('Ashe', 'The Frost Archer', 'F'),
('Azir', 'The Emperor of the Sands', 'M'),
('Bard', 'The Wandering Caretaker', 'M'),
('Blitzcrank', 'The Great Steam Golem', 'M'),
('Brand', 'The Burning Vengeance', 'M'),
('Braum', 'The Heart of the Freljord', 'M'),
('Caitlyn', 'The Sheriff of Piltover', 'F'),
('Cassiopeia', 'The Serpents Embrace', 'F'),
('ChoGath', 'The Terror of the Void', 'M'),
('Corki', 'The Daring Bombardier', 'M'),
('Darius', 'The Hand of Noxus', 'M'),
('Diana', 'Scorn of the Moon', 'F'),
('Dr. Mundo', 'The Madman of Zaun', 'M'),
('Draven', 'The Glorious Executioner', 'M'),
('Elise', 'The Spider Queen', 'F'),
('Evelynn', 'The Widowmaker', 'F'),
('Ezreal', 'The Prodigal Explorer', 'M'),
('Fiddlesticks', 'The Harbinger of Doom', 'M'),
('Fiora', 'The Grand Duelist', 'F'),
('Fizz', 'The Tidal Trickster', 'M'),
('Galio', 'The Sentinels Sorrow', 'M'),
('Gangplank', 'The Saltwater Scourge', 'M'),
('Garen', 'The Might of Demacia', 'M'),
('Gnar', 'The Missing Link', 'M'),
('Gragas', 'The Rabble Rouser', 'M'),
('Graves', 'The Outlaw', 'M'),
('Hecarim', 'The Shadow of War', 'M'),
('Heimerdinger', 'The Revered Inventor', 'M'),
('Irelia', 'The Will of the Blades', 'F'),
('Janna', 'The Storms Fury', 'F'),
('Jarvan IV', 'The Exemplar of Demacia', 'M'),
('Jax', 'Grandmaster at Arms', 'M'),
('Jayce', 'The Defender of Tomorrow', 'M'),
('Jinx', 'The Loose Cannon', 'F'),
('Kalista', 'The Spear of Vengeance', 'F'),
('Karma', 'The Enlightened One', 'F'),
('Karthus', 'The Deathsinger', 'M'),
('Kassadin', 'The Void Walker', 'M'),
('Katarina', 'The Sinister Blade', 'F'),
('Kayle', 'The Judicator', 'F'),
('Kennen', 'The Heart of the Tempest', 'M'),
('KhaZix', 'The Voidreaver', 'M'),
('KogMaw', 'The Mouth of the Abyss', 'M'),
('LeBlanc', 'The Deceiver', 'F'),
('Lee Sin', 'The Blind Monk', 'M'),
('Leona', 'The Radiant Dawn', 'F'),
('Lissandra', 'The Ice Witch', 'F'),
('Lucian', 'The Purifier', 'M'),
('Lulu', 'The Fae Sorceress', 'F'),
('Lux', 'The Lady of Luminosity', 'F'),
('Malphite', 'Shard of the Monolith', 'M'),
('Malzahar', 'The Prophet of the Void', 'M'),
('Maokai', 'The Twisted Treant', 'M'),
('Master Yi', 'The Wuju Bladesman', 'M'),
('Miss Fortune', 'the Bounty Hunter', 'F'),
('Mordekaiser', 'The Master of Metal', 'M'),
('Morgana', 'Fallen Angel', 'F'),
('Nami', 'The Tidecaller', 'F'),
('Nasus', 'The Curator of the Sands', 'M'),
('Nautilus', 'The Titan of the Depths', 'M'),
('Nidalee', 'The Bestial Huntress', 'F'),
('Nocturne', 'The Eternal Nightmare', 'M'),
('Nunu', 'The Yeti Rider', 'M')