use LoLDb;

insert into Skills values
('Blood Well','passive',0),
('Dark Flight','active',0),
('Blood Thirst','passive',0),
('Blades of Torment','active',75),
('Massacre','active',200),
('Essence Theft','passive',0),
('Orb of Deception','active',40),
('Fox-Fire','active',40),
('Charm','active',60),
('Spirit Rush','active',70),
('Twin Disciplines','passive',0),
('Mark of the Assassin','active',35),
('Twilight Shroud','active',0),
('Crescent Slash','active',30),
('Shadow Dance','active',100),
('Trample','passive',0),
('Pulverize','active',60),
('Headbutt','active',55),
('Triumphant Roar','active',0),
('Unbreakable Will','active',0),
('Cursed Touch','passive',0),
('Bandage Toss','active',80),
('Despair','active',8),
('Tantrum','active',75),
('Curse of the Sad Mummy','active',150),
('Rebirth','passive',0),
('Flash Frost','active',60),
('Crystallize','active',0),
('Frostbite','active',55),
('Glacial Storm','active',80),
('Pyromania','passive',0),
('Disintegrate','active',80),
('Incinerate','active',70),
('Molten Shield','active',20),
('Summon: Tibbers','active',175),
('Focus','passive',0),
('Frost Shot','active',0),
('Volley','active',40),
('Hawkshot','active',0),
('Enchanted Crystal Arrow','active',250),
('Shurimas Legacy','passive',0),
('Conquering Sands','active',65),
('Arise!','active',0),
('Shifting Sands','active',60),
('Emperors Divide','active',150),
('Travelers Call','passive',0),
('Cosmic Binding','active',80),
('Caretakers Shrine','active',0),
('Magical Journey','active',0),
('Tempered Fate','active',0),
('Mana Barrier','passive',0),
('Rocket Grab','active',80),
('Overdrive','active',0),
('Power Fist','active',0),
('Static Field','active',250),
('Blaze','passive',0),
('Sear','active',80),
('Pillar of Flame','active',75),
('Conflagration','active',70),
('Pyroclasm','active',150),
('Concussive Blows','passive',0),
('Winters Bite','active',60),
('Stand Behind Me','active',0),
('Unbreakable','active',0),
('Glacial Fissure','active',150),
('Headshot','passive',0),
('Piltover Peacemaker','active',20),
('Yordle Snap Trap','active',80),
('90 Caliber Net','active',80),
('Ace in the Hole','active',250),
('Aspect of the Serpent','passive',0),
('Noxious Blast','active',25),
('Miasma','active',10),
('Twin Fang','active',55),
('Petrifying Gaze','active',150),
('Carnivore','passive',0),
('Rupture','active',80),
('Feral Scream','active',75),
('Vorpal Spikes','active',20),
('Feast','active',300),
('Hextech Shrapnel Shells','passive',0),
('Phosphorus Bomb','active',80),
('Valkyrie','active',30),
('Gatling Gun','active',20),
('Missile Barrage','active',100),
('Hemorrhage','passive',0),
('Decimate','active',70),
('Crippling Strike','active',20),
('Apprehend','active',0),
('Noxian Guillotine','active',160),
('Moonsilver Blade','passive',0),
('Crescent Strike','active',60),
('Pale Cascade','active',22),
('Moonfall','active',0),
('Lunar Rush','active',100),
('Adrenaline Rush','passive',0),
('Infected Cleaver','active',80),
('Burning Agony','active',35),
('Masochism','active',0),
('Sadism','active',0),
('League of Draven','passive',0),
('Spinning Axe','active',45),
('Blood Rush','active',0),
('Stand Aside','active',70),
('Whirling Death','active',175),
('Spider Swarm','passive',0),
('Neurotoxin','active',40),
('Volatile Spiderling','active',75),
('Cocoon','active',0),
('Spider Form','active',0),
('Shadow Walk','passive',0),
('Hate Spike','active',40),
('Dark Frenzy','active',0),
('Ravage','active',35),
('Agonys Embrace','active',15),
('Rising Spell Force','passive',0),
('Mystic Shot','active',35),
('Essence Flux','active',70),
('Arcane Shift','active',75),
('Trueshot Barrage','active',350),
('Dread','passive',0),
('Terrify','active',0),
('Drain','active',60),
('Dark Wind','active',65),
('Crowstorm','active',125),
('Duelist','passive',0),
('Lunge','active',40),
('Riposte','active',15),
('Burst of Speed','active',0),
('Blade Waltz','active',125),
('Nimble Fighter','passive',0),
('Urchin Strike','active',10),
('Seastone Trident','active',20),
('Playful','active',70),
('Chum the Waters','active',200),
('Runic Skin','passive',0),
('Resolute Smite','active',80),
('Bulwark','active',0),
('Righteous Gust','active',60),
('Idol of Durand','active',220),
('Grog Soaked Blade','passive',0),
('Parrrley','active',20),
('Remove Scurvy','active',0),
('Raise Morale','active',0),
('Cannon Barrage','active',75),
('Perseverance','passive',0),
('Decisive Strike','active',30),
('Courage','active',0),
('Judgment','active',20),
('Demacian Justice','active',175),
('Rage Gene','passive',0),
('Boomerang Throw','active',5),
('Hyper','active',10),
('Hop','active',0),
('GNAR!','active',200),
('Happy Hour','passive',0),
('Barrel Roll','active',80),
('Drunken Rage','active',0),
('Body Slam','active',80),
('Explosive Cask','active',200),
('True Grit','passive',0),
('Buckshot','active',60),
('Smoke Screen','active',60),
('Quickdraw','active',0),
('Collateral Damage','active',250),
('Warpath','passive',0),
('Rampage','active',60),
('Spirit of Dread','active',20),
('Devastating Charge','active',40),
('Onslaught of Shadows','active',150),
('Techmaturgical Repair Bots','passive',0),
('H-28G Evolution Turret','active',12),
('Hextech Micro-Rockets','active',60),
('CH-2 Electron Storm Grenade','active',60),
('UPGRADE!!!','active',0),
('Ionian Fervor', 'Passive', 0),
('Bladesurge', 'Active', 20),
('Hiten Style', 'Active', 15),
('Equilibrium Strike', 'Active', 80),
('Transcendent Blades', 'Active', 80),
('Tailwind', 'Passive', 0),
('Howling Gale', 'Active', 60),
('Zephyr', 'Active', 60),
('Eye of the Storm', 'Active', 0),
('Monsoon', 'Active', 0),
('Martial Cadence', 'Passive', 0),
('Dragon Strike', 'Active', 70),
('Golden Aegis', 'Active', 0),
('Demacian Standard', 'Active', 60),
('Cataclysm', 'Active', 200),
('Relentless Assault', 'Passive', 0),
('Leap Strike', 'Active', 70),
('Empower', 'Active', 40),
('Counter Strike', 'Active', 50),
('Grandmasters Might', 'Active', 100),
('Hextech Capacitor', 'Passive', 0),
('To The Skies!', 'Active', 20),
('Shock Blast', 'Active', 60),
('Lightning Field', 'Active', 100),
('Hyper Charge', 'Active', 0),
('Thundering Blow', 'Active', 8),
('Acceleration Gate', 'Active', 0),
('Transform: Mercury Cannon', 'Active', 0),
('Transform: Mercury Hammer', 'Active', 0),
('Get Excited!', 'Passive', 0),
('Switcheroo!', 'Active', 0),
('Zap!', 'Active', 10),
('Flame Chompers!', 'Active', 80),
('Super Mega Death Rocket!', 'Active', 125),
('Martial Poise', 'Passive', 0),
('Pierce', 'Active', 10),
('Sentinel', 'Active', 12),
('Rend', 'Active', 20),
('Fates Call', 'Active', 0),
('Gathering Fire', 'Passive', 0),
('Inner Flame', 'Active', 80),
('Soulflare', 'Passive', 25),
('Focused Resolve', 'Active', 60),
('Renewal', 'Passive', 75),
('Inspire', 'Active', 0),
('Defiance', 'Passive', 60),
('Mantra', 'Active', 0),
('Death Defied', 'Passive', 0),
('Lay Waste', 'Active', 40),
('Wall of Pain', 'Active', 0),
('Defile', 'Active', 30),
('Requiem', 'Active', 250),
('Void Stone', 'Passive', 0),
('Null Sphere', 'Active', 70),
('Nether Blade', 'Active', 40),
('Force Pulse', 'Active', 80),
('Riftwalk', 'Active', 80),
('Voracity', 'Passive', 0),
('Bouncing Blades', 'Active', 60),
('Sinister Steel', 'Active', 40),
('Shunpo', 'Active', 60),
('Death Lotus', 'Active', 35),
('Holy Fervor', 'Passive', 0),
('Reckoning', 'Active', 60),
('Divine Blessing', 'Active', 0),
('Righteous Fury', 'Active', 20),
('Intervention', 'Active', 0),
('Mark of the Storm', 'Passive', 0),
('Thundering Shuriken', 'Active', 75),
('Electrical Surge', 'Active', 40),
('Lightning Rush', 'Active', 85),
('Slicing Maelstrom', 'Active', 80),
('Unseen Threat', 'Passive', 0),
('Taste Their Fear', 'Active', 70),
('Evolved Enlarged Claws', 'Passive', 91),
('Void Spike', 'Active', 80),
('Evolved Spike Racks', 'Passive', 0),
('Leap', 'Active', 65),
('Evolved Wings', 'Passive', 0),
('Void Assault', 'Active', 0),
('Evolved Active Camouflage', 'Passive', 0),
('Icathian Surprise', 'Passive', 0),
('Caustic Spittle', 'Active', 80),
('Bio-Arcane Barrage', 'Active', 2),
('Void Ooze', 'Active', 60),
('Living Artillery', 'Active', 80),
('Mirror Image', 'Passive', 0),
('Sigil of Malice', 'Active', 55),
('Distortion', 'Active', 85),
('Ethereal Chains', 'Active', 40),
('Mimic', 'Active', 0),
('Flurry', 'Passive', 0),
('Sonic Wave', 'Active', 50),
('Resonating Strike', 'Active', 50),
('Safeguard', 'Active', 0),
('Iron Will', 'Active', 0),
('Tempest', 'Active', 60),
('Cripple', 'Active', 0),
('Dragons Rage', 'Active', 200),
('Sunlight', 'Passive', 0),
('Shield of Daybreak', 'Active', 40),
('Eclipse', 'Active', 60),
('Zenith Blade', 'Active', 60),
('Solar Flare', 'Active', 150),
('Iceborn', 'Passive', 0),
('Ice Shard', 'Active', 70),
('Ring of Frost', 'Active', 70),
('Glacial Path', 'Active', 70),
('Frozen Tomb', 'Active', 150),
('Lightslinger', 'Passive', 0),
('Piercing Light', 'Active', 80),
('Ardent Blaze', 'Active', 60),
('Relentless Pursuit', 'Active', 0),
('The Culling', 'Active', 40),
('Pix, Faerie Companion', 'Passive', 0),
('Glitterlance', 'Active', 80),
('Whimsy', 'Active', 0),
('Help, Pix!', 'Active', 80),
('Wild Growth', 'Active', 0),
('Illumination', 'Passive', 0),
('Light Binding', 'Active', 60),
('Prismatic Barrier', 'Active', 0),
('Lucent Singularity', 'Active', 60),
('Final Spark', 'Active', 300),
('Granite Shield', 'Passive', 0),
('Seismic Shard', 'Active', 70),
('Brutal Strikes', 'Active', 30),
('Ground Slam', 'Active', 60),
('Unstoppable Force', 'Active', 200),
('Summon Voidling', 'Passive', 0),
('Call of the Void', 'Active', 80),
('Null Zone', 'Active', 20),
('Malefic Visions', 'Active', 80),
('Nether Grasp', 'Active', 250),
('Sap Magic', 'Passive', 0),
('Arcane Smash', 'Active', 70),
('Twisted Advance', 'Active', 9),
('Sapling Toss', 'Active', 40),
('Vengeful Maelstrom', 'Active', 100),
('Double Strike', 'Passive', 0),
('Alpha Strike', 'Active', 25),
('Meditate', 'Active', 0),
('Wuju Style', 'Active', 10),
('Highlander', 'Active', 0),
('Strut', 'Passive', 0),
('Double Up', 'Active', 20),
('Impure Shots', 'Active', 0),
('Make It Rain', 'Active', 90),
('Bullet Time', 'Active', 36),
('Iron Man', 'Passive', 0),
('Mace of Spades', 'Active', 80),
('Creeping Death', 'Active', 20),
('Siphon of Destruction', 'Active', 70),
('Children of the Grave', 'Active', 12),
('Soul Siphon', 'Passive', 0),
('Dark Binding', 'Active', 80),
('Tormented Soil', 'Active', 12),
('Black Shield', 'Active', 0),
('Soul Shackles', 'Active', 150),
('Surging Tides', 'Passive', 0),
('Aqua Prison', 'Active', 75),
('Ebb and Flow', 'Active', 70),
('Tidecallers Blessing', 'Active', 75),
('Tidal Wave', 'Active', 150),
('Soul Eater', 'Passive', 0),
('Siphoning Strike', 'Active', 30),
('Wither', 'Active', 0),
('Spirit Fire', 'Active', 55),
('Fury of the Sands', 'Active', 45),
('Staggering Blow', 'Passive', 0),
('Dredge Line', 'Active', 60),
('Titans Wrath', 'Active', 30),
('Riptide', 'Active', 60),
('Depth Charge', 'Active', 125),
('Prowl', 'Passive', 0),
('Javelin Toss', 'Active', 50),
('Takedown', 'Active', 4),
('Bushwhack', 'Active', 40),
('Pounce', 'Active', 50),
('Primal Surge', 'Active', 0),
('Swipe', 'Active', 70),
('Aspect of the Cougar', 'Active', 0),
('Umbra Blades', 'Passive', 0),
('Duskbringer', 'Active', 60),
('Shroud of Darkness', 'Active', 0),
('Unspeakable Horror', 'Active', 50),
('Paranoia', 'Active', 150),
('Visionary', 'Passive', 0),
('Consume', 'Active', 400),
('Blood Boil', 'Active', 0),
('Ice Blast', 'Active', 85),
('Absolute Zero', 'Active', 625);