use LoLDb;

insert into Equipment values
('Amplifying Tome','','+20 Ability Power'),
('Ancient Coin','Passive Unique: Favor: Being near a minion death without dealing the killing blow grants 2 gold and heals for 5 health. (Limited to 1 gold income item)','+25% Mana Regen per 5 seconds'),
('B.F. Sword','','+50 Attack Damage'),
('Blasting Wand','','+40 Ability Power'),
('Boots of Speed','Passive Unique: Enhanced Movement: +25 movement speed',''),
('Brawlers Gloves','','+8% Critical Strike Chance'),
('Cloak of Agility','','+15% Critical Strike Chance'),
('Cloth Armor','','+15 Armor'),
('Dagger','','+15% Attack Speed'),
('Dorans Blade','','+70 Health +7 Attack Damage  +3% Lifesteal'),
('Dorans Ring','Passive	Restores 4 mana when you kill an enemy unit','+60 Health +15 Ability Power +3 Mana Regen per 5 seconds'),
('Dorans Shield','Passive Restores 6 Health every 5 seconds. Unique: Blocks 8 damage from single target attacks and spells from champions.','+80 Health'),
('Faerie Charm','','+25% Mana Regen per 5 seconds'),
('Hunters Machete','Passive	Deal 30 magic damage on-hit to Monsters over 2 seconds and gain 7 Health and 3 Mana per second while in combat with Monsters.',''),
('Long Sword','','+10 Attack Damage'),
('Needlessly Large Rod','','+80 Ability Power'),
('Null-Magic Mantle','','+25 Magic Resist'),
('Pickaxe','','+25 Attack Damage'),
('Prospectors Blade','Passive Unique: Prospector','+16 Attack Damage +15% Attack Speed'),
('Prospectors Ring','Passive Unique: Prospector','+35 Ability Power +6 Mana Regen per 5 seconds'),
('Recurve Bow','','+30% Attack Speed'),
('Rejuvenation Bead','','+50% Health Regen per 5 seconds'),
('Relic Shield','Passive Unique: Spoils of War','+75 Health'),
('Ruby Crystal','','+150 Health'),
('Sapphire Crystal','','+200 Mana'),
('Spellthiefs Edge','Passive Unique: Tribute','+5 Ability Power +25% Mana Regen per 5 seconds +2 Gold per 10 seconds'),
('Prototype Hex Core','Viktor starts with this item in his inventory and he cannot sell it. It cannot be bought by anyone. This Item can be upgraded three times to enhance ViktorSquare.png Viktor''s basic abilities.','+3 ability power per level.'),
('The Black Spear', '',' Kalista starts with this item in her inventory and she cannot sell it. It cannot be bought by anyone. Upon use the item disappears.'),
('Aegis of the Legion','Aura	Unique ¨C Legion: Nearby allied champions gain +20 magic resist and +75% health regen per 5 seconds. (1100 range)','+200 health +20 magic resistance'),
('Aether Wisp','Passive	Unique: +5% movement speed','+30 ability power'),
('Avarice Blade','Passive	Unique: Avarice Passive	Unique: Greed','+10% critical strike chance'),
('Berserkers Greaves','Passive Unique: Enhanced Movement','+25% attack speed'),
('Boots of Mobility','Passive Unique: Enhanced Movement. Increases to +105 movement speed when out of combat for 5 seconds.',''),
('Boots of Swiftness','Passive	Unique: Enhanced Movement Passive	Unique: Slow Resist',''),
('The Brutalizer','','+25 attack damage'),
('Catalyst the Protector','Passive	Unique: Valor''s Reward','+200 health +300 mana'),
('Chain Vest','','+40 armor'),
('Chalice of Harmony','Passive	Unique: Mana Font','+25 magic resistance +50% mana regeneration'),
('Crystalline Bracer','','+200 health  +50% health regeneration per 5 seconds'),
('Fiendish Codex','Passive	Unique: 10% cooldown reduction','+30 ability power'),
('Forbidden Idol','Passive	Unique: +10% cooldown reduction','+60% mana regeneration'),
('Frostfang','Passive	Unique: Tribute (Limited to 1 Gold income item)','+10 ability power +50% mana regeneration per 5 seconds +2 Gold per 10 seconds'),
('Giants Belt','','+380 health'),
('Glacial Shroud','Passive	Unique: +10% cooldown reduction','+250 mana +20 armor'),
('Guardians Horn','Passive	Unique: Nearby enemy spell casts reduce the cooldown of Battle Cry by 1 second. Active	Unique: Battle Cry','+180 health +100% health regeneration'),
('Guinsoos Rageblade','Passive	Your basic attacks or spellcasts grant you 4% attack speed and +4 Ability power for 8 seconds. This bonus stacks up to 8 times. Passive	UNIQUE: Falling below 50% health grants you 20% attack speed, 10% life steal, and 10% spell vamp until you exit combat. (30 second cooldown)','+30 attack damage +40 ability power'),
('Haunting Guise','Passive	Unique: Eyes of Pain','+200 health +25 ability power'),
('Hexdrinker','Passive	Unique: Lifeline','+25 attack damage +30 magic resistance'),
('Hextech Revolver','Passive	Unique: +12% Spell Vamp','+40 ability power'),
('Infinity Edge','Passive	Unique: Critical strikes deal 250% damage instead of 200%.','+80 attack damage +25% critical strike chance'),
('Ionian Boots of Lucidity','Passive	Unique: Enhanced Movement Passive	Unique: +15% cooldown reduction',''),
('Kindlegem','Passive	Unique: 10% cooldown reduction','+200 health'),
('Last Whisper','Passive	Unique: Ignores 35% of your opponents armor','+40 attack damage'),
('Madrayylmaos Razors','Passive	Unique - Maim: Basic attacks against monsters deal 50 bonus magic damage and restore 8 health.','+15% attack speed'),
('Mejais Soulstealer','Passive	Unique: Your champion gains 8 ability power per stack, receiving 2 stacks for a kill or 1 stack for an assist. This effect can stack 20 times; you lose a third of your stacks if you die. At 20 stacks, your champion''s cooldowns are reduced by 15%.','+20 ability power'),
('Mercurys Treads','Passive	Unique: Enhanced Movement Passive	Unique: Tenacity','+25 magic resistance'),
('Negatron Cloak','','+45 magic resistance'),
('Ninja Tabi','Passive	Unique: Enhanced Movement Passive	Unique: Blocks 10% of the damage from all basic attacks.','+25 armor'),
('Nomads Medallion','Passive	Unique: Favor (Limited to 1 Gold income item)','+25% health regeneration per 5 seconds +25% mana regeneration per 5 seconds +10 movement speed +2 Gold per 10 seconds'),
('Orb of Winter','Passive	Unique: Grants a shield that absorbs up to 30 + (10 per level) damage. This shield refreshes after 9 seconds without receiving damage.','+70 magic resistance +100% health regeneration per 5 seconds'),
('Phage','Passive	Unique: Rage','+200 health +20 attack damage'),
('Poachers Knife','Passive	Unique: Scavenging Smite Passive	Unique: Jungler',''),
('Quicksilver Sash','Active	Unique: Quicksilver','+30 magic resistance'),
('Rabadons Deathcap','Passive	Unique: Increases ability power by 30%.','+120 ability power'),
('Rangers Trailblazer','Passive	Unique: Blasting Smite Passive	Unique: Jungler',''),
('Raptor Cloak','Passive	Unique - Point Runner: Builds up to 30% Movement Speed over 2 seconds while near turrets.','+30 armor  +100% health regeneration per 5 seconds'),
('Runaans Hurricane','Passive	Unique: Your basic attacks fire minor bolts at two nearby targets, each dealing 10 + 50% of your attack damage. These apply on-hit effects.','+70% attack speed'),
('Seekers Armguard','Passive	Unique: Kills grant 0.5 bonus armor and ability power. This bonus stacks up to 30 times.','+30 armor +20 ability power'),
('Sheen','Passive	Unique: Spellblade','+200 mana +25 ability power'),
('Sightstone','Passive	Unique: Ward Refresh Active	Unique: Ghost Ward','+150 health'),
('Skirmishers Sabre','Passive	Unique: Challenging Smite Passive	Unique: Jungler',''),
('Sorcerers Shoes','Passive	Unique: Enhanced Movement','+15 magic penetration'),
('Spectres Cowl','Passive	Unique: Grants 100% Health regeneration per 5 seconds for up to 10 seconds after taking damage from an enemy champion.','+200 health +35 magic resistance'),
('Stalkers Blade','Passive	Unique: Chilling Smite Passive	Unique: Jungler',''),
('Stinger','Passive	Unique: 10% cooldown reduction','+40% attack speed'),
('Sword of the Occult','Passive	Unique: Your champion gains +5 damage per stack, receiving 2 stacks for a kill or 1 stack for an assist. This effect can stack 20 times; you lose a third of your stacks if you die. At 20 stacks, your champion''s movement speed is increased 15%.','+10 attack damage'),
('Targons Brace','Passive	Unique: Spoils of War (Limited to 1 Gold income item)','+175 health +50% health regeneration per 5 seconds'),
('Tear of the Goddess','Passive	Unique: Mana Charge','+250 mana +25% mana regeneration per 5 seconds'),
('Tiamat','Active	Unique: Crescent Passive	Unique: Cleave','+40 attack damage +100% health regeneration per 5 seconds'),
('Vampiric Scepter','','+10 attack damage +8% life steal'),
('Void Staff','Passive	Unique: 35% magic penetration.','+70 ability power'),
('Wardens Mail','Passive	Unique: Cold Steel','+45 armor'),
('Wicked Hatchet','Passive	Unique Passive: Critical strikes causes your target to bleed for an additional 60% of your bonus AD as physical damage over 3 seconds.','+20 attack damage +10% critical strike chance'),
('Wits End','Passive	Unique: Your attacks deal 42 bonus magic damage. Passive	Unique: Your attacks increase your magic resistance by 5 for 5 seconds and reduce the target''s magic resistance by 5 on hit (stacks up to 5 times).','+50% attack Speed +30 magic resistance'),
('Zeal','','+20% attack speed +10% critical strike chance +5% movement speed'),
('The Hex Core mk-1','Passive UNIQUE - PROGRESS: ViktorSquare.png Viktor can upgrade one of his basic spells.','+4 ability per level +20 ability power +100 mana'),
('Abyssal Scepter','UNIQUE Aura: Reduces the Magic Resist of nearby enemies by 20.','+70 Ability Power +50 Magic Resist'),
('Archangels Staff','Passive	Unique: Insight Passive	Unique: Mana Charge - This item transforms once it reaches +750 Mana, gaining a powerful mana shield active.','+250 mana +50% mana regen +60 ability power'),
('Ardent Censer','Passive	Unique: +8% movement speed. Passive	Unique: Your heals and shields on another unit grant them 25% attack speed for 6 seconds. This does not include regeneration effects or effects on yourself.','+40 ability power +100% mana regen +10% cooldown reduction'),
('Athenes Unholy Grail','Passive	Unique: Restores 15% of your max mana on kill or assist. Passive	Unique: Mana Font','+60 ability power +25 magic resistance +50% mana regen +20% cooldown reduction'),
('Banner of Command','Active	Unique: Promote Aura	Unique: Legion','+200 health +60 ability power +20 magic resist +10% cooldown reduction'),
('Banshees Veil','Passive	Unique: Gain a spell shield that blocks the next incoming enemy ability. This shield refreshes if you haven''t taken damage from champions in 25 seconds.','+450 health +55 magic resistance +100% health regeneration'),
('Bilgewater Cutlass','Active	Unique: Deals 100 magic damage and slows the target champion''s movement speed by 25% for 2 seconds (500 range). 90 second cooldown.','+25 attack damage +8% life steal'),
('The Black Cleaver','Passive	Unique: +10 armor penetration Passive	Unique: Dealing physical damage to an enemy champion reduces their armor by 5% for 4 seconds. (This effect stacks up to 5 times with 25% maximum reduction.)','+200 health +50 attack damage +10% cooldown reduction'),
('The Bloodthirster','Passive	Unique: Your life steal overheals you, converting the excess healing into a shield that absorbs up to 50-450 damage and decays when out of combat for 15 seconds.','+80 attack damage +15% life steal'),
('Dervish Blade','Active	Unique: Quicksilver','+50% attack speed +45 magic resist +10% cooldown reduction'),
('Entropy','Passive	Unique: Rage Active	Unique: For the next 5 seconds, your attacks reduce your target''s movement speed by 30% and deal 80 true damage over 2.5 seconds. (60 second cooldown)','+55 attack damage +275 health'),
('Essence Reaver','Active	Unique: Your basic attacks restore mana equal to between 2% and 8% of the physical damage dealt, based on your missing mana.','+80 attack damage +10% life steal +10% cooldown reduction'),
('Face of the Mountain','Passive	Unique: Spoils of War. You may only be in possession of 1 Gold Income item. Active	Unique - Deadly Phalanx: You shield the target ally for 10% of your maximum health for 4 seconds. After 4 seconds, the shield explodes, dealing magic damage equal to (100% of the target''s AD) + (30% of the target''s AP), regardless of if the shield remained intact. 60 second cooldown.','+500 health +100% health regeneration +10% cooldown reduction'),
('Frost Queens Claim','Passive	Unique: Tribute Active	UNIQUE - Arctic Embrace: Fire an ice lance that detonates at the target location, dealing 50 (+5 per level) magic damage to enemies and slowing them by 80%, decaying over 2 seconds. 60 second cooldown. (850 range, 225 radius)','+50 ability power +10% cooldown reduction +50% mana regeneration +2 gold per 10 seconds'),
('Frozen Heart','Aura	Unique: Reduces the attack speed of nearby enemies by 15%.','+100 armor +400 mana +20% cooldown reduction'),
('Frozen Mallet','Passive	Unique: Icy','+30 attack damage +700 health'),
('Grezs Spectral Lantern','Passive	Unique: Maim Passive	Unique: Gain 30% increased gold from monsters. Passive	Unique: Trap Detection: Nearby stealthed enemy traps are revealed. Active	Unique: A stealth-detecting mist grants vision in the target area for 5 seconds and reveals enemies that enter it for 3 seconds. 60 second cooldown. (800 Range, 375 AOE estimate).','+15 attack damage +30% attack speed'),
('Guardian Angel','Passive	Unique: Revives your champion upon death, restoring 30% of your maximum heath and mana (5 minute cooldown)','+50 armor +40 magic resistance'),
('Hextech Sweeper','Passive	Unique: +20% cooldown reduction Passive	Unique: Trap Detection Active	Unique: Covers an area with stealth-detecting mist for 5 seconds, granting vision of units which pass through it for 3 seconds. 60 second cooldown. (800 Range, 375 AOE estimate).','+225 health +25 armor +250 mana'),
('Iceborn Gauntlet','Passive	Unique: Spellblade','+10% cooldown reduction +30 ability power +60 armor +500 mana'),
('Liandrys Torment','Passive	Unique: Eyes of Pain Passive	Unique: Dealing spell damage applies a damage-over-time effect that deals bonus magic damage equal to 2% of the target''s current health per second for 3 seconds. This bonus damage is doubled against movement-impaired units and capped at 100 damage per second vs. monsters.','+50 ability power +300 health'),
('Lich Bane','Passive	Unique: Spellblade','+80 ability power +250 mana +5% movement speed'),
('The Lightbringer','Passive	Unique: Critical Vision Passive	Unique: Trap Detection','+30 damage +30% attack speed'),
('Locket of the Iron Solari','Aura	Unique: Legion Active	Unique: Shield yourself and nearby allied champions for 5 seconds, absorbing up to 50 (+10 per level) damage. 60 second cooldown. (600 range)','+400 health +20 magic resistance +10% cooldown reduction'),
('Lord Van Damms Pillager','Passive	Unique Passive: +50% critical strike damage','+80 attack damage +25% critical strike chance'),
('Manamune','Passive	Unique: Awe Passive	Unique: Mana Charge - Item transforms when bonus mana reaches 750.','+20 attack damage +250 mana +25% mana regen'),
('Maw of Malmortius','Passive	Unique: Gain +1 attack damage for every 2% of your maximum health you are missing, capped at 35 attack damage. Passive	Unique: Lifeline','+60 attack damage +40 magic resistance'),
('Mercurial Scimitar','Active	Unique: Quicksilver','+80 attack damage +45 magic resistance'),
('Mikaels Crucible','Active	Unique Active: Removes all stuns, roots, taunts, fears, silences and slows on an allied champion and heals for 150 + 10% of the target''s maximum health. (180 second cooldown) Passive	Unique: Mana Font','+40 magic resistance +100% mana regen +10% cooldown reduction'),
('Moonflair Spellblade','Passive	Unique Passive - Tenacity','+50 ability power +50 armor +50 magic resistance'),
('Morellonomicon','Passive	Unique: Dealing magic damage to an enemy champion below 40% health inflicts Grievous Wounds to them for 4 seconds.','+80 ability power +100% mana regen +20% cooldown reduction'),
('Nashors Tooth','Passive	Unique: +20% cooldown reduction Passive	Unique: Basic attacks deal 15 (+15% AP) bonus magic damage on hit','+60 Ability power +50% attack speed'),
('Odyns Veil','Passive	Unique: Reduces and stores 10% of the magic damage dealt to your champion. Active	Unique: Deals 200 + (stored magic) [max: 400] to nearby enemy units. (90 second cooldown. 525 Range estimate)','+350 health +50 magic resistance +350 mana'),
('Ohmwrecker','Passive	Unique Passive: Builds up to 30% Movement Speed over 2 seconds while near turrets. Active	Unique Active: Prevents the closest enemy tower from attacking for 3 seconds (120 second cooldown). This effect cannot be used against the same tower more than once every 8 seconds.','+300 health +50 armor +100% health regeneration per 5 seconds +10% cooldown reduction'),
('Overlords Bloodmail','Passive	Unique: On kill or assist, gain 200 HP over 5 seconds.','+850 health'),
('Phantom Dancer','Passive	Unique: Your champion ignores unit collision.','+50% attack speed +35% critical strike chance 5% movement speed'),
('Randuins Omen','Passive	Unique: Cold Steel Active	Unique: Slows the movement speed of surrounding enemies by 35% for 2 seconds + 1 second for every 100 armor and magic resistance you have. (60 second cooldown. 500 range)','+500 Health +70 Armor'),
('Ravenous Hydra','Passive	Damage dealt by this item works with life steal. Passive	Unique: Cleave Active	Unique: Crescent','+75 attack damage +100% health regen +12% life steal'),
('Righteous Glory','Passive	Unique: Valor''s Reward Active	Unique: Grants +60% Movement Speed to you and nearby allies when moving towards enemies for 3 seconds. When this speed boost ends, it emits a shockwave, slowing nearby enemy champions by 80% for one second (60s cooldown).','+500 health +300 mana +100% health regen'),
('Rod of Ages','Passive	This item gains 20 Health, 20 Mana, and 2 Ability Power every minute, up to 10 times. Passive	Unique: Valor''s Reward','+60 ability power +450 health +450 mana'),
('Ruby Sightstone','Passive	Unique: Ward Refresh Active	Unique: Ghost Ward','+400 health'),
('Rylais Crystal Scepter','Passive	Unique: Your spell damage will slow the target''s movement speed by 35% for 1.5 seconds (15% for multi-target spells and damage-over-time spells).','+100 ability power +400 health'),
('Sanguine Blade','Passive	Unique: Your basic attacks grant 6 attack damage and 1% lifesteal. This buff stacks up to 5 times and lasts for 8 seconds.','+45 attack damage +10% life steal'),
('Spirit Visage','Passive	Unique: Increases self-healing, health regen, Lifesteal and Spellvamp effects by 20%.','+400 health +55 magic resistance +10% cooldown reduction +100% health regen'),
('Statikk Shiv','Passive	Unique: Moving and attacking build Static Charges. At 100 charges, your next attack expends the Charge to deal 100 Magic damage to up to 4 targets. This damage can critically strike.','+40% attack speed +20% Critical strike chance +6% movement speed'),
('Sunfire Cape','Passive	Unique passive: Deals 25 + (1 x level) magic damage per second to nearby enemies (400 range).','+450 health +45 armor'),
('Talisman of Ascension','Passive	Unique: Favor Active	UNIQUE: Grants nearby allies +40% movement speed for 3 seconds. 60 second cooldown. (600 range)','+2 gold per 10 seconds +100% health regen +100% Mana regen +20% cooldown reduction'),
('Thornmail','Passive	Unique: On being hit by basic attacks, returns 30% of damage taken as magic damage. A minimum 15 damage must be received.','+100 armor'),
('Trinity Force','Passive	Unique: Rage Passive	Unique: Spellblade','+30 ability power +30 attack damage +30% attack speed +10% critical strike chance +250 health +200 mana +8% movement speed'),
('Twin Shadows','Active	Unique: Hunt','+80 ability power +10% cooldown reduction +6% movement speed'),
('Warmog''s Armor','Passive	UNIQUE: Restores 1% of your maximum health every 5 seconds. Health restore increases to 3% of maximum health if damage hasn''t been taken within 8 seconds.','+800 health'),
('Will of the Ancients','Passive	Unique: +20% spell vamp','+80 ability power +10% cooldown reduction'),
('Wooglets Witchcap','Active	Unique: Places your champion into stasis for 2.5 seconds, rendering you invulnerable and untargetable but unable to take any action. (90 second cooldown) Passive	Unique: Increase ability power by 25%.','+100 Ability power +45 Armor'),
('Youmuus Ghostblade','Active	Unique: Gain 20% movement speed and 40% attack speed for 6 seconds. (45 second cooldown) Passive	Unique: +20 armor penetration','+30 attack damage +15% critical strike chance +10% cooldown reduction'),
('Zekes Herald','Aura	Unique: Nearby allied champions gain 10% Life Steal and 20 Attack Damage.','+250 health +20% cooldown reduction'),
('Zephyr','Passive	Unique: Tenacity','+25 attack damage +50% attack speed +10% movement speed +10% cooldown reduction'),
('Zhonyas Hourglass','Active	Unique: Stasis','+120 ability Power +50 armor'),
('ZzRot Portal','Passive	Unique: Point Runner Active	Unique: Spawns a Void Gate at target location for 150 seconds. Every 4 seconds the gate creates a volatile Voidspawn that travels down the nearest lane, attacking enemy minions and exploding when attacking structures, but ignoring champions and void targets. (150 second cooldown)','+50 armor +50 magic resistance +100% health regen'),
('The Hex Core mk-2','Passive UNIQUE - PROGRESS: ViktorSquare.png Viktor can upgrade one of his basic spells.','+5 ability per level +40 ability power +300 mana'),
('Blade of the Ruined King','Passive	UNIQUE: Your attacks deal 8% of the target''s current health in physical damage (60 max vs minions and monsters. Active	UNIQUE: Drains target champion, dealing 10% of the champion''s maximum health in physical damage and healing you by the same amount. Additionally you steal 25% of their movement speed for 3 seconds - 90 second cooldown. (450 range)','+25 attack damage +10% life steal +40% attack speed'),
('Hextech Gunblade','Passive	UNIQUE: +20% spell vamp Passive	UNIQUE: Reload: Your basic attacks (on hit) and single-target spells against champions reduce the cooldown of this item by 3 seconds. Active	UNIQUE: Deals 150 (+ 40% AP) magic damage and slows the target champion''s movement speed by 40% for 2 seconds. 60 second cooldown. (700 range)','+40 attack damage +80 ability power +10% life steal'),
('Muramana','Passive	UNIQUE - Awe: Gain attack damage equal to 2% of your maximum mana. Active	Toggle: Your single target spells and attacks consume 3% of your current mana to deal 6% of your current mana as physical damage.','+1000 mana +25 attack damage +25% mana regen'), ('Seraphs Embrace','Passive	UNIQUE - Insight: Gain ability power equal to 3% of your maximum mana. Active	UNIQUE - Mana Shield: Drains 25% of your current mana to shield yourself for an equal amount for 3 seconds (120 second cooldown).','+1000 mana +60 ability power +50% mana regen per 5 seconds'),
('Perfect Hex Core','Passive UNIQUE - GLORIOUS EVOLUTION: ViktorSquare.png Viktor has reached the pinnacle of his power, upgrading Chaos Storm.png Chaos Storm in addition to his basic spells.','+6 ability per level +60 ability power +500 mana'),
('Crystalline Flask','Effect	Starts with 3 charges and refills each time you stop by your shop.  Consumes a charge to restore 120 health and 60 mana over 12 seconds. Stacks	1 per item slot. ',''),
('Elixir of Iron','Effect	Grants 25% increased size, slow resistance, Tenacity and Path of Iron for 3 minutes. Stacks	3 per item slot.',''),
('Elixir of Ruin','Effect	Grants 250 health, 15% bonus damage to towers and Siege Commander for 3 minutes. Stacks	3 per item slot.',''),
('Elixir of Sorcery','Effect	Grants +40 ability power, 15 bonus mana regen and Sorcery for 3 minutes. Stacks	3 per item slot.',''),
('Elixir of Wrath','Effect	Grants +25 attack damage and Bloodlust for 3 minutes. Bloodlust: Dealing physical damage to champions heals for 10% of the damage dealt. Scoring a kill or assist extends duration of this elixir by 30 seconds. Stacks	3 per item slot.',''),
('Health Potion','Effect	Restores 150 health over the time of 15 seconds. Stacks	5 per item slot.',''),
('Mana Potion','Effect	Restores 100 mana over the time of 15 seconds. Stacks	5 per item slot.',''),
('Oracles Extract','Effect	Grants your Champion stealth detection for 5 minutes or until they die Stacks	1 per item slot.',''),
('Poro-Snax','Effect	Serves a scrumptious scoop to a nearby Poro. Stacks	1 per item slot.',''),
('Stealth Ward','Effect	Places an invisible ward with 3 health and 1100 sight range. Lasts 180 seconds. Stacks	Limit of 3 per player inventory (1 item slot) Limit of 3 placed on the map per player',''),
('Total Biscuit of Rejuvenation','Effect	Restores 20 Health and 10 Mana on consumption, and 150 health over 15 seconds. Stacks	5 per item slot.',''),
('Vision Ward','Effect	Places a visible ward with 5 health. Ward has 1000 sight range with Magical Sight (can see invisible units) and have infinite duration. Stacks	Limit of 2 per player inventory (1 item slot) Limit of 1 placed on the map per player','');